name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  install:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: cargo-registry-cache

    - name: Install dependencies
      run: |
        # downloads dependencies without creating compiling
        cargo fetch 

  build:

    runs-on: ubuntu-latest
    needs: install

    steps:

    - uses: actions/checkout@v4
    - uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: Cache cargo build
      uses: actions/cache@v4
      with:
        path: target
        key: cargo-build-cache
        restore-keys: |
          cargo-build-cache

    - name: Install target
      run: rustup target add x86_64-unknown-linux-gnu

    - name: Build
      run: cargo build --release --target x86_64-unknown-linux-gnu

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: target/release/
